version: '2'

services:
  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:1.19.2
    ports: [5775:5775/udp, 6831:6831/udp, 6832:6832/udp, 5778:5778, 16686:16686, 14268:14268, 9411:9411]

  zookeeper:
    container_name: zookeeper
    image: docker.io/bitnami/zookeeper:3-debian-10
    ports: [2181:2181]
    environment: [ALLOW_ANONYMOUS_LOGIN=yes]

  kafka:
    container_name: kafka
    image: docker.io/bitnami/kafka:2-debian-10
    ports: [9092:9092]
    environment:
    - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
    - ALLOW_PLAINTEXT_LISTENER=yes
    - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
    - KAFKA_CFG_LISTENERS=CLIENT://:9091,EXTERNAL://:9092
    - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9091,EXTERNAL://localhost:9092
    - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
    - zookeeper

  akhq:
    container_name: akhq
    ports: [8080:8080]
    image: tchiotludo/akhq
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            kafka:
              properties:
                bootstrap.servers: kafka:9091
